// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package io_radicalbit_nsdb_rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Dimension struct {
	// Types that are valid to be assigned to Value:
	//	*Dimension_DecimalValue
	//	*Dimension_LongValue
	//	*Dimension_StringValue
	Value                isDimension_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Dimension) Reset()         { *m = Dimension{} }
func (m *Dimension) String() string { return proto.CompactTextString(m) }
func (*Dimension) ProtoMessage()    {}
func (*Dimension) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Dimension) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dimension.Unmarshal(m, b)
}
func (m *Dimension) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dimension.Marshal(b, m, deterministic)
}
func (m *Dimension) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dimension.Merge(m, src)
}
func (m *Dimension) XXX_Size() int {
	return xxx_messageInfo_Dimension.Size(m)
}
func (m *Dimension) XXX_DiscardUnknown() {
	xxx_messageInfo_Dimension.DiscardUnknown(m)
}

var xxx_messageInfo_Dimension proto.InternalMessageInfo

type isDimension_Value interface {
	isDimension_Value()
}

type Dimension_DecimalValue struct {
	DecimalValue float64 `protobuf:"fixed64,1,opt,name=decimalValue,proto3,oneof"`
}

type Dimension_LongValue struct {
	LongValue int64 `protobuf:"varint,2,opt,name=longValue,proto3,oneof"`
}

type Dimension_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=stringValue,proto3,oneof"`
}

func (*Dimension_DecimalValue) isDimension_Value() {}

func (*Dimension_LongValue) isDimension_Value() {}

func (*Dimension_StringValue) isDimension_Value() {}

func (m *Dimension) GetValue() isDimension_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Dimension) GetDecimalValue() float64 {
	if x, ok := m.GetValue().(*Dimension_DecimalValue); ok {
		return x.DecimalValue
	}
	return 0
}

func (m *Dimension) GetLongValue() int64 {
	if x, ok := m.GetValue().(*Dimension_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Dimension) GetStringValue() string {
	if x, ok := m.GetValue().(*Dimension_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Dimension) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Dimension_DecimalValue)(nil),
		(*Dimension_LongValue)(nil),
		(*Dimension_StringValue)(nil),
	}
}

type Tag struct {
	// Types that are valid to be assigned to Value:
	//	*Tag_DecimalValue
	//	*Tag_LongValue
	//	*Tag_StringValue
	Value                isTag_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

type isTag_Value interface {
	isTag_Value()
}

type Tag_DecimalValue struct {
	DecimalValue float64 `protobuf:"fixed64,1,opt,name=decimalValue,proto3,oneof"`
}

type Tag_LongValue struct {
	LongValue int64 `protobuf:"varint,2,opt,name=longValue,proto3,oneof"`
}

type Tag_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=stringValue,proto3,oneof"`
}

func (*Tag_DecimalValue) isTag_Value() {}

func (*Tag_LongValue) isTag_Value() {}

func (*Tag_StringValue) isTag_Value() {}

func (m *Tag) GetValue() isTag_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Tag) GetDecimalValue() float64 {
	if x, ok := m.GetValue().(*Tag_DecimalValue); ok {
		return x.DecimalValue
	}
	return 0
}

func (m *Tag) GetLongValue() int64 {
	if x, ok := m.GetValue().(*Tag_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Tag) GetStringValue() string {
	if x, ok := m.GetValue().(*Tag_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Tag) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Tag_DecimalValue)(nil),
		(*Tag_LongValue)(nil),
		(*Tag_StringValue)(nil),
	}
}

type Bit struct {
	Timestamp int64 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*Bit_DecimalValue
	//	*Bit_LongValue
	Value                isBit_Value           `protobuf_oneof:"value"`
	Dimensions           map[string]*Dimension `protobuf:"bytes,4,rep,name=dimensions,proto3" json:"dimensions,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Tags                 map[string]*Tag       `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Bit) Reset()         { *m = Bit{} }
func (m *Bit) String() string { return proto.CompactTextString(m) }
func (*Bit) ProtoMessage()    {}
func (*Bit) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{2}
}

func (m *Bit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bit.Unmarshal(m, b)
}
func (m *Bit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bit.Marshal(b, m, deterministic)
}
func (m *Bit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bit.Merge(m, src)
}
func (m *Bit) XXX_Size() int {
	return xxx_messageInfo_Bit.Size(m)
}
func (m *Bit) XXX_DiscardUnknown() {
	xxx_messageInfo_Bit.DiscardUnknown(m)
}

var xxx_messageInfo_Bit proto.InternalMessageInfo

func (m *Bit) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

type isBit_Value interface {
	isBit_Value()
}

type Bit_DecimalValue struct {
	DecimalValue float64 `protobuf:"fixed64,2,opt,name=decimalValue,proto3,oneof"`
}

type Bit_LongValue struct {
	LongValue int64 `protobuf:"varint,3,opt,name=longValue,proto3,oneof"`
}

func (*Bit_DecimalValue) isBit_Value() {}

func (*Bit_LongValue) isBit_Value() {}

func (m *Bit) GetValue() isBit_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Bit) GetDecimalValue() float64 {
	if x, ok := m.GetValue().(*Bit_DecimalValue); ok {
		return x.DecimalValue
	}
	return 0
}

func (m *Bit) GetLongValue() int64 {
	if x, ok := m.GetValue().(*Bit_LongValue); ok {
		return x.LongValue
	}
	return 0
}

func (m *Bit) GetDimensions() map[string]*Dimension {
	if m != nil {
		return m.Dimensions
	}
	return nil
}

func (m *Bit) GetTags() map[string]*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Bit) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Bit_DecimalValue)(nil),
		(*Bit_LongValue)(nil),
	}
}

func init() {
	proto.RegisterType((*Dimension)(nil), "io.radicalbit.nsdb.rpc.Dimension")
	proto.RegisterType((*Tag)(nil), "io.radicalbit.nsdb.rpc.Tag")
	proto.RegisterType((*Bit)(nil), "io.radicalbit.nsdb.rpc.Bit")
	proto.RegisterMapType((map[string]*Dimension)(nil), "io.radicalbit.nsdb.rpc.Bit.DimensionsEntry")
	proto.RegisterMapType((map[string]*Tag)(nil), "io.radicalbit.nsdb.rpc.Bit.TagsEntry")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x92, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0x9b, 0xa6, 0x55, 0x32, 0x2d, 0x28, 0x39, 0x48, 0xa9, 0x22, 0x6b, 0x51, 0x58, 0x10,
	0x02, 0xd6, 0x83, 0x7f, 0x8e, 0x45, 0xa1, 0xe0, 0x2d, 0x2c, 0x9e, 0x4d, 0x77, 0x97, 0x25, 0xb8,
	0x49, 0x96, 0x4d, 0x14, 0x7b, 0xf1, 0x43, 0xf9, 0x09, 0xa5, 0x69, 0xbb, 0xdd, 0xda, 0x56, 0x8f,
	0xde, 0xc2, 0x63, 0xe6, 0xf7, 0x66, 0xe6, 0x05, 0xba, 0xb1, 0x51, 0xca, 0x68, 0x56, 0x94, 0xc6,
	0x19, 0x7a, 0x24, 0x0d, 0x2b, 0x45, 0x22, 0x63, 0x91, 0x4f, 0xa4, 0x63, 0xda, 0x26, 0x13, 0x56,
	0x16, 0xf1, 0xe0, 0x13, 0xc8, 0x83, 0x54, 0xa9, 0xb6, 0xd2, 0x68, 0x7a, 0x0e, 0xdd, 0x24, 0x8d,
	0xa5, 0x12, 0xf9, 0xb3, 0xc8, 0xdf, 0xd2, 0x1e, 0x0a, 0x50, 0x88, 0xc6, 0x0d, 0xbe, 0xa6, 0xd2,
	0x53, 0x20, 0xb9, 0xd1, 0xd9, 0xbc, 0xa4, 0x19, 0xa0, 0x10, 0x8f, 0x1b, 0x7c, 0x25, 0xd1, 0x01,
	0x74, 0xac, 0x2b, 0xe5, 0xb2, 0x02, 0x07, 0x28, 0x24, 0xe3, 0x06, 0xaf, 0x8b, 0xa3, 0x7d, 0x68,
	0xbf, 0xcf, 0x1e, 0x83, 0x0f, 0xc0, 0x91, 0xc8, 0xfe, 0xc3, 0xf9, 0x0b, 0x03, 0x1e, 0x49, 0x47,
	0x4f, 0x80, 0x38, 0xa9, 0x52, 0xeb, 0x84, 0x2a, 0xbc, 0x2f, 0xe6, 0x2b, 0x61, 0x63, 0xb0, 0xe6,
	0xdf, 0x83, 0xe1, 0xcd, 0xc1, 0x9e, 0x00, 0x92, 0xe5, 0x95, 0x6d, 0xaf, 0x15, 0xe0, 0xb0, 0x33,
	0xbc, 0x64, 0xdb, 0x23, 0x61, 0x23, 0xe9, 0x58, 0x95, 0x89, 0x7d, 0xd4, 0xae, 0x9c, 0xf2, 0x5a,
	0x3b, 0xbd, 0x83, 0x96, 0x13, 0x99, 0xed, 0xb5, 0x3d, 0xe6, 0xe2, 0x37, 0x4c, 0x24, 0xb2, 0x05,
	0xc0, 0xb7, 0xf4, 0x5f, 0xe0, 0xe0, 0x07, 0x99, 0x1e, 0x02, 0x7e, 0x4d, 0xa7, 0x7e, 0x71, 0xc2,
	0x67, 0x4f, 0x7a, 0xb3, 0xb8, 0x90, 0xdf, 0xb5, 0x33, 0x3c, 0xdb, 0x65, 0x50, 0x91, 0xf8, 0xbc,
	0xfe, 0xbe, 0x79, 0x8b, 0xfa, 0x11, 0x90, 0xca, 0x74, 0x0b, 0xfb, 0x6a, 0x9d, 0x7d, 0xbc, 0x8b,
	0x1d, 0x89, 0xac, 0x46, 0xad, 0x42, 0x9b, 0xec, 0xf9, 0xdf, 0x7c, 0xfd, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0x05, 0xad, 0xaf, 0x50, 0xdd, 0x02, 0x00, 0x00,
}
