// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dump.proto

package io_radicalbit_nsdb_rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DumpTarget struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpTarget) Reset()         { *m = DumpTarget{} }
func (m *DumpTarget) String() string { return proto.CompactTextString(m) }
func (*DumpTarget) ProtoMessage()    {}
func (*DumpTarget) Descriptor() ([]byte, []int) {
	return fileDescriptor_58418148159c29a6, []int{0}
}

func (m *DumpTarget) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpTarget.Unmarshal(m, b)
}
func (m *DumpTarget) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpTarget.Marshal(b, m, deterministic)
}
func (m *DumpTarget) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpTarget.Merge(m, src)
}
func (m *DumpTarget) XXX_Size() int {
	return xxx_messageInfo_DumpTarget.Size(m)
}
func (m *DumpTarget) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpTarget.DiscardUnknown(m)
}

var xxx_messageInfo_DumpTarget proto.InternalMessageInfo

func (m *DumpTarget) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *DumpTarget) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type DumpRequest struct {
	Targets              []*DumpTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	DestPath             string        `protobuf:"bytes,2,opt,name=destPath,proto3" json:"destPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DumpRequest) Reset()         { *m = DumpRequest{} }
func (m *DumpRequest) String() string { return proto.CompactTextString(m) }
func (*DumpRequest) ProtoMessage()    {}
func (*DumpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58418148159c29a6, []int{1}
}

func (m *DumpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpRequest.Unmarshal(m, b)
}
func (m *DumpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpRequest.Marshal(b, m, deterministic)
}
func (m *DumpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpRequest.Merge(m, src)
}
func (m *DumpRequest) XXX_Size() int {
	return xxx_messageInfo_DumpRequest.Size(m)
}
func (m *DumpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpRequest proto.InternalMessageInfo

func (m *DumpRequest) GetTargets() []*DumpTarget {
	if m != nil {
		return m.Targets
	}
	return nil
}

func (m *DumpRequest) GetDestPath() string {
	if m != nil {
		return m.DestPath
	}
	return ""
}

type DumpResponse struct {
	StartedSuccessfully  bool     `protobuf:"varint,1,opt,name=startedSuccessfully,proto3" json:"startedSuccessfully,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	DumpPath             string   `protobuf:"bytes,3,opt,name=dumpPath,proto3" json:"dumpPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpResponse) Reset()         { *m = DumpResponse{} }
func (m *DumpResponse) String() string { return proto.CompactTextString(m) }
func (*DumpResponse) ProtoMessage()    {}
func (*DumpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58418148159c29a6, []int{2}
}

func (m *DumpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpResponse.Unmarshal(m, b)
}
func (m *DumpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpResponse.Marshal(b, m, deterministic)
}
func (m *DumpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpResponse.Merge(m, src)
}
func (m *DumpResponse) XXX_Size() int {
	return xxx_messageInfo_DumpResponse.Size(m)
}
func (m *DumpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpResponse proto.InternalMessageInfo

func (m *DumpResponse) GetStartedSuccessfully() bool {
	if m != nil {
		return m.StartedSuccessfully
	}
	return false
}

func (m *DumpResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func (m *DumpResponse) GetDumpPath() string {
	if m != nil {
		return m.DumpPath
	}
	return ""
}

type RestoreRequest struct {
	SourcePath           string   `protobuf:"bytes,4,opt,name=sourcePath,proto3" json:"sourcePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreRequest) Reset()         { *m = RestoreRequest{} }
func (m *RestoreRequest) String() string { return proto.CompactTextString(m) }
func (*RestoreRequest) ProtoMessage()    {}
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_58418148159c29a6, []int{3}
}

func (m *RestoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreRequest.Unmarshal(m, b)
}
func (m *RestoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreRequest.Marshal(b, m, deterministic)
}
func (m *RestoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreRequest.Merge(m, src)
}
func (m *RestoreRequest) XXX_Size() int {
	return xxx_messageInfo_RestoreRequest.Size(m)
}
func (m *RestoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreRequest proto.InternalMessageInfo

func (m *RestoreRequest) GetSourcePath() string {
	if m != nil {
		return m.SourcePath
	}
	return ""
}

type RestoreResponse struct {
	StartedSuccessfully  bool     `protobuf:"varint,1,opt,name=startedSuccessfully,proto3" json:"startedSuccessfully,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestoreResponse) Reset()         { *m = RestoreResponse{} }
func (m *RestoreResponse) String() string { return proto.CompactTextString(m) }
func (*RestoreResponse) ProtoMessage()    {}
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_58418148159c29a6, []int{4}
}

func (m *RestoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestoreResponse.Unmarshal(m, b)
}
func (m *RestoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestoreResponse.Marshal(b, m, deterministic)
}
func (m *RestoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestoreResponse.Merge(m, src)
}
func (m *RestoreResponse) XXX_Size() int {
	return xxx_messageInfo_RestoreResponse.Size(m)
}
func (m *RestoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestoreResponse proto.InternalMessageInfo

func (m *RestoreResponse) GetStartedSuccessfully() bool {
	if m != nil {
		return m.StartedSuccessfully
	}
	return false
}

func (m *RestoreResponse) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *RestoreResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*DumpTarget)(nil), "io.radicalbit.nsdb.rpc.DumpTarget")
	proto.RegisterType((*DumpRequest)(nil), "io.radicalbit.nsdb.rpc.DumpRequest")
	proto.RegisterType((*DumpResponse)(nil), "io.radicalbit.nsdb.rpc.DumpResponse")
	proto.RegisterType((*RestoreRequest)(nil), "io.radicalbit.nsdb.rpc.RestoreRequest")
	proto.RegisterType((*RestoreResponse)(nil), "io.radicalbit.nsdb.rpc.RestoreResponse")
}

func init() { proto.RegisterFile("dump.proto", fileDescriptor_58418148159c29a6) }

var fileDescriptor_58418148159c29a6 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x52, 0x4f, 0x4b, 0x3b, 0x31,
	0x10, 0x65, 0xdb, 0xf2, 0x6b, 0x3b, 0xfd, 0x51, 0x21, 0x82, 0x94, 0x22, 0x52, 0xa2, 0x68, 0x4f,
	0xa1, 0xd4, 0x9b, 0x78, 0xd3, 0xab, 0x20, 0xab, 0x20, 0x78, 0xcb, 0x26, 0x63, 0x2d, 0x74, 0x9b,
	0x98, 0x49, 0x40, 0x3f, 0x9b, 0x5f, 0x4e, 0x9a, 0x66, 0x5b, 0x17, 0x6a, 0x05, 0x6f, 0xfb, 0x66,
	0xdf, 0x9f, 0x79, 0xb3, 0x0b, 0xa0, 0x43, 0x69, 0x85, 0x75, 0xc6, 0x1b, 0x76, 0x34, 0x37, 0xc2,
	0x49, 0x3d, 0x57, 0x72, 0x51, 0xcc, 0xbd, 0x58, 0x92, 0x2e, 0x84, 0xb3, 0x8a, 0x5f, 0x01, 0xdc,
	0x86, 0xd2, 0x3e, 0x4a, 0x37, 0x43, 0xcf, 0xfa, 0xd0, 0xd0, 0xc5, 0x20, 0x1b, 0x65, 0xe3, 0x6e,
	0xde, 0xd0, 0x05, 0x3b, 0x86, 0xee, 0x52, 0x96, 0x48, 0x56, 0x2a, 0x1c, 0x34, 0xe2, 0x78, 0x3b,
	0xe0, 0x33, 0xe8, 0xad, 0xb4, 0x39, 0xbe, 0x05, 0x24, 0xcf, 0xae, 0xa1, 0xed, 0xa3, 0x0d, 0x0d,
	0xb2, 0x51, 0x73, 0xdc, 0x9b, 0x72, 0xb1, 0x3b, 0x54, 0x6c, 0x13, 0xf3, 0x4a, 0xc2, 0x86, 0xd0,
	0xd1, 0x48, 0xfe, 0x5e, 0xfa, 0xd7, 0x94, 0xb4, 0xc1, 0xfc, 0x1d, 0xfe, 0xaf, 0x83, 0xc8, 0x9a,
	0x25, 0x21, 0x9b, 0xc0, 0x21, 0x79, 0xe9, 0x3c, 0xea, 0x87, 0xa0, 0x14, 0x12, 0xbd, 0x84, 0xc5,
	0xe2, 0x23, 0xee, 0xdd, 0xc9, 0x77, 0xbd, 0x5a, 0xb9, 0xa3, 0x73, 0xc6, 0xdd, 0xd1, 0xac, 0x72,
	0xaf, 0x70, 0x4c, 0x0e, 0xa5, 0x8d, 0xc9, 0xcd, 0x94, 0x9c, 0x30, 0x9f, 0x40, 0x3f, 0x47, 0xf2,
	0xc6, 0x61, 0xd5, 0xf2, 0x04, 0x80, 0x4c, 0x70, 0x0a, 0x23, 0xbf, 0x15, 0xf9, 0xdf, 0x26, 0x9c,
	0xe0, 0x60, 0xa3, 0xf8, 0xf3, 0xba, 0x0c, 0x5a, 0x76, 0x7b, 0x88, 0xf8, 0x5c, 0xab, 0xd0, 0xac,
	0x57, 0x98, 0x7e, 0x66, 0xd0, 0x5a, 0x5d, 0x88, 0x3d, 0x01, 0xdc, 0x38, 0x94, 0x1e, 0x23, 0x3a,
	0xdd, 0xf7, 0x01, 0x52, 0xa1, 0xe1, 0xd9, 0x7e, 0x52, 0xea, 0xf0, 0x0c, 0xed, 0x54, 0x8b, 0x9d,
	0xff, 0x24, 0xa8, 0x5f, 0x6a, 0x78, 0xf1, 0x2b, 0x6f, 0xed, 0x5d, 0xfc, 0x8b, 0xbf, 0xe8, 0xe5,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x39, 0x07, 0xdf, 0xbd, 0xb0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DumpClient is the client API for Dump service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DumpClient interface {
	CreateDump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*DumpResponse, error)
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
}

type dumpClient struct {
	cc *grpc.ClientConn
}

func NewDumpClient(cc *grpc.ClientConn) DumpClient {
	return &dumpClient{cc}
}

func (c *dumpClient) CreateDump(ctx context.Context, in *DumpRequest, opts ...grpc.CallOption) (*DumpResponse, error) {
	out := new(DumpResponse)
	err := c.cc.Invoke(ctx, "/io.radicalbit.nsdb.rpc.Dump/CreateDump", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dumpClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, "/io.radicalbit.nsdb.rpc.Dump/Restore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DumpServer is the server API for Dump service.
type DumpServer interface {
	CreateDump(context.Context, *DumpRequest) (*DumpResponse, error)
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
}

// UnimplementedDumpServer can be embedded to have forward compatible implementations.
type UnimplementedDumpServer struct {
}

func (*UnimplementedDumpServer) CreateDump(ctx context.Context, req *DumpRequest) (*DumpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDump not implemented")
}
func (*UnimplementedDumpServer) Restore(ctx context.Context, req *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}

func RegisterDumpServer(s *grpc.Server, srv DumpServer) {
	s.RegisterService(&_Dump_serviceDesc, srv)
}

func _Dump_CreateDump_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DumpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DumpServer).CreateDump(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.radicalbit.nsdb.rpc.Dump/CreateDump",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DumpServer).CreateDump(ctx, req.(*DumpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dump_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DumpServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.radicalbit.nsdb.rpc.Dump/Restore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DumpServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dump_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.radicalbit.nsdb.rpc.Dump",
	HandlerType: (*DumpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDump",
			Handler:    _Dump_CreateDump_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _Dump_Restore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dump.proto",
}
