// Code generated by protoc-gen-go. DO NOT EDIT.
// source: init.proto

package io_radicalbit_nsdb_rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InitMetricRequest struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Metric               string   `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	ShardInterval        string   `protobuf:"bytes,4,opt,name=shardInterval,proto3" json:"shardInterval,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitMetricRequest) Reset()         { *m = InitMetricRequest{} }
func (m *InitMetricRequest) String() string { return proto.CompactTextString(m) }
func (*InitMetricRequest) ProtoMessage()    {}
func (*InitMetricRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{0}
}

func (m *InitMetricRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMetricRequest.Unmarshal(m, b)
}
func (m *InitMetricRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMetricRequest.Marshal(b, m, deterministic)
}
func (m *InitMetricRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMetricRequest.Merge(m, src)
}
func (m *InitMetricRequest) XXX_Size() int {
	return xxx_messageInfo_InitMetricRequest.Size(m)
}
func (m *InitMetricRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMetricRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitMetricRequest proto.InternalMessageInfo

func (m *InitMetricRequest) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *InitMetricRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InitMetricRequest) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *InitMetricRequest) GetShardInterval() string {
	if m != nil {
		return m.ShardInterval
	}
	return ""
}

type InitMetricResponse struct {
	Db                    string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace             string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Metric                string   `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	CompletedSuccessfully bool     `protobuf:"varint,4,opt,name=completedSuccessfully,proto3" json:"completedSuccessfully,omitempty"`
	ErrorMsg              string   `protobuf:"bytes,5,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *InitMetricResponse) Reset()         { *m = InitMetricResponse{} }
func (m *InitMetricResponse) String() string { return proto.CompactTextString(m) }
func (*InitMetricResponse) ProtoMessage()    {}
func (*InitMetricResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d036da5b4a9bcf3, []int{1}
}

func (m *InitMetricResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitMetricResponse.Unmarshal(m, b)
}
func (m *InitMetricResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitMetricResponse.Marshal(b, m, deterministic)
}
func (m *InitMetricResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitMetricResponse.Merge(m, src)
}
func (m *InitMetricResponse) XXX_Size() int {
	return xxx_messageInfo_InitMetricResponse.Size(m)
}
func (m *InitMetricResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InitMetricResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InitMetricResponse proto.InternalMessageInfo

func (m *InitMetricResponse) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *InitMetricResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *InitMetricResponse) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *InitMetricResponse) GetCompletedSuccessfully() bool {
	if m != nil {
		return m.CompletedSuccessfully
	}
	return false
}

func (m *InitMetricResponse) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*InitMetricRequest)(nil), "io.radicalbit.nsdb.rpc.InitMetricRequest")
	proto.RegisterType((*InitMetricResponse)(nil), "io.radicalbit.nsdb.rpc.InitMetricResponse")
}

func init() { proto.RegisterFile("init.proto", fileDescriptor_8d036da5b4a9bcf3) }

var fileDescriptor_8d036da5b4a9bcf3 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0xd9, 0x55, 0x8f, 0xbb, 0x01, 0x05, 0x03, 0x1e, 0xe1, 0xb0, 0x90, 0xc3, 0x42, 0x2d,
	0x52, 0xa8, 0x2f, 0x71, 0xc5, 0x35, 0xeb, 0x13, 0xe4, 0xcf, 0xa8, 0x81, 0x6c, 0x92, 0x9b, 0xc9,
	0x0a, 0x56, 0xbe, 0x90, 0x0f, 0x29, 0x44, 0xf1, 0x5c, 0xdc, 0xc2, 0xc2, 0xf2, 0xfb, 0xbe, 0x99,
	0xe1, 0xc7, 0x37, 0x00, 0x3e, 0xfa, 0xa2, 0x32, 0xa5, 0x92, 0xc4, 0xd2, 0x27, 0x45, 0xda, 0x79,
	0xab, 0x83, 0xf1, 0x45, 0x45, 0x76, 0x46, 0x51, 0xb6, 0xeb, 0x37, 0x38, 0xdd, 0x44, 0x5f, 0xb6,
	0x58, 0xc8, 0xdb, 0x0e, 0x77, 0x03, 0x72, 0x11, 0x27, 0xd0, 0x3a, 0x23, 0x9b, 0x8b, 0xe6, 0x6a,
	0xd1, 0xb5, 0xce, 0x88, 0x73, 0x58, 0x44, 0xdd, 0x23, 0x67, 0x6d, 0x51, 0xb6, 0xd5, 0xde, 0x1b,
	0x62, 0x09, 0xb3, 0xbe, 0xae, 0xcb, 0x83, 0x1a, 0x7d, 0x29, 0x71, 0x09, 0xc7, 0xfc, 0xac, 0xc9,
	0x6d, 0x62, 0x41, 0x7a, 0xd1, 0x41, 0x1e, 0xd6, 0x78, 0x6c, 0xae, 0xdf, 0x1b, 0x10, 0x3f, 0x09,
	0x38, 0xa7, 0xc8, 0xf8, 0x4f, 0x08, 0xf7, 0x70, 0x66, 0x53, 0x9f, 0x03, 0x16, 0x74, 0x0f, 0x83,
	0xb5, 0xc8, 0xfc, 0x38, 0x84, 0xf0, 0x5a, 0x51, 0xe6, 0xdd, 0x74, 0x28, 0x56, 0x30, 0x47, 0xa2,
	0x44, 0x5b, 0x7e, 0x92, 0x47, 0xf5, 0xde, 0xb7, 0xbe, 0xdd, 0x01, 0xec, 0x69, 0x85, 0x1d, 0xa9,
	0x6b, 0x35, 0x5d, 0xb2, 0xfa, 0xd5, 0xf0, 0xea, 0xe6, 0x2f, 0xa3, 0x9f, 0x55, 0x98, 0x59, 0xfd,
	0xe0, 0xdd, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0x74, 0xcc, 0x36, 0x8c, 0xcf, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InitMetricClient is the client API for InitMetric service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InitMetricClient interface {
	InitMetric(ctx context.Context, in *InitMetricRequest, opts ...grpc.CallOption) (*InitMetricResponse, error)
}

type initMetricClient struct {
	cc *grpc.ClientConn
}

func NewInitMetricClient(cc *grpc.ClientConn) InitMetricClient {
	return &initMetricClient{cc}
}

func (c *initMetricClient) InitMetric(ctx context.Context, in *InitMetricRequest, opts ...grpc.CallOption) (*InitMetricResponse, error) {
	out := new(InitMetricResponse)
	err := c.cc.Invoke(ctx, "/io.radicalbit.nsdb.rpc.InitMetric/InitMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitMetricServer is the server API for InitMetric service.
type InitMetricServer interface {
	InitMetric(context.Context, *InitMetricRequest) (*InitMetricResponse, error)
}

// UnimplementedInitMetricServer can be embedded to have forward compatible implementations.
type UnimplementedInitMetricServer struct {
}

func (*UnimplementedInitMetricServer) InitMetric(ctx context.Context, req *InitMetricRequest) (*InitMetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitMetric not implemented")
}

func RegisterInitMetricServer(s *grpc.Server, srv InitMetricServer) {
	s.RegisterService(&_InitMetric_serviceDesc, srv)
}

func _InitMetric_InitMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitMetricServer).InitMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.radicalbit.nsdb.rpc.InitMetric/InitMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitMetricServer).InitMetric(ctx, req.(*InitMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _InitMetric_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.radicalbit.nsdb.rpc.InitMetric",
	HandlerType: (*InitMetricServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitMetric",
			Handler:    _InitMetric_InitMetric_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "init.proto",
}
