// Code generated by protoc-gen-go. DO NOT EDIT.
// source: requestCommand.proto

package io_radicalbit_nsdb_rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShowMetrics struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowMetrics) Reset()         { *m = ShowMetrics{} }
func (m *ShowMetrics) String() string { return proto.CompactTextString(m) }
func (*ShowMetrics) ProtoMessage()    {}
func (*ShowMetrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_47af1abd2632bd2f, []int{0}
}

func (m *ShowMetrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowMetrics.Unmarshal(m, b)
}
func (m *ShowMetrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowMetrics.Marshal(b, m, deterministic)
}
func (m *ShowMetrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowMetrics.Merge(m, src)
}
func (m *ShowMetrics) XXX_Size() int {
	return xxx_messageInfo_ShowMetrics.Size(m)
}
func (m *ShowMetrics) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowMetrics.DiscardUnknown(m)
}

var xxx_messageInfo_ShowMetrics proto.InternalMessageInfo

func (m *ShowMetrics) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *ShowMetrics) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type DescribeMetric struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Metric               string   `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeMetric) Reset()         { *m = DescribeMetric{} }
func (m *DescribeMetric) String() string { return proto.CompactTextString(m) }
func (*DescribeMetric) ProtoMessage()    {}
func (*DescribeMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_47af1abd2632bd2f, []int{1}
}

func (m *DescribeMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeMetric.Unmarshal(m, b)
}
func (m *DescribeMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeMetric.Marshal(b, m, deterministic)
}
func (m *DescribeMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeMetric.Merge(m, src)
}
func (m *DescribeMetric) XXX_Size() int {
	return xxx_messageInfo_DescribeMetric.Size(m)
}
func (m *DescribeMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeMetric.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeMetric proto.InternalMessageInfo

func (m *DescribeMetric) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *DescribeMetric) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *DescribeMetric) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

type ShowNamespaces struct {
	Db                   string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowNamespaces) Reset()         { *m = ShowNamespaces{} }
func (m *ShowNamespaces) String() string { return proto.CompactTextString(m) }
func (*ShowNamespaces) ProtoMessage()    {}
func (*ShowNamespaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_47af1abd2632bd2f, []int{2}
}

func (m *ShowNamespaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowNamespaces.Unmarshal(m, b)
}
func (m *ShowNamespaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowNamespaces.Marshal(b, m, deterministic)
}
func (m *ShowNamespaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowNamespaces.Merge(m, src)
}
func (m *ShowNamespaces) XXX_Size() int {
	return xxx_messageInfo_ShowNamespaces.Size(m)
}
func (m *ShowNamespaces) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowNamespaces.DiscardUnknown(m)
}

var xxx_messageInfo_ShowNamespaces proto.InternalMessageInfo

func (m *ShowNamespaces) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func init() {
	proto.RegisterType((*ShowMetrics)(nil), "io.radicalbit.nsdb.rpc.ShowMetrics")
	proto.RegisterType((*DescribeMetric)(nil), "io.radicalbit.nsdb.rpc.DescribeMetric")
	proto.RegisterType((*ShowNamespaces)(nil), "io.radicalbit.nsdb.rpc.ShowNamespaces")
}

func init() { proto.RegisterFile("requestCommand.proto", fileDescriptor_47af1abd2632bd2f) }

var fileDescriptor_47af1abd2632bd2f = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x71, 0xce, 0xcf, 0xcd, 0x4d, 0xcc, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x12, 0xcb, 0xcc, 0xd7, 0x2b, 0x4a, 0x4c, 0xc9, 0x4c, 0x4e, 0xcc, 0x49, 0xca, 0x2c, 0xd1,
	0xcb, 0x2b, 0x4e, 0x49, 0xd2, 0x2b, 0x2a, 0x48, 0x56, 0xb2, 0xe6, 0xe2, 0x0e, 0xce, 0xc8, 0x2f,
	0xf7, 0x4d, 0x2d, 0x29, 0xca, 0x4c, 0x2e, 0x16, 0xe2, 0xe3, 0x62, 0x4a, 0x49, 0x92, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x4a, 0x49, 0x12, 0x92, 0xe1, 0xe2, 0xcc, 0x4b, 0xcc, 0x4d, 0x2d,
	0x2e, 0x48, 0x4c, 0x4e, 0x95, 0x60, 0x02, 0x0b, 0x23, 0x04, 0x94, 0xc2, 0xb8, 0xf8, 0x5c, 0x52,
	0x8b, 0x93, 0x8b, 0x32, 0x93, 0x52, 0x21, 0x06, 0x90, 0xa6, 0x5f, 0x48, 0x8c, 0x8b, 0x2d, 0x17,
	0xac, 0x4f, 0x82, 0x19, 0x2c, 0x05, 0xe5, 0x29, 0x29, 0x70, 0xf1, 0x81, 0x1c, 0xe5, 0x07, 0x53,
	0x88, 0xe1, 0xae, 0x24, 0x36, 0xb0, 0xaf, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x13, 0x7f,
	0x89, 0xae, 0xed, 0x00, 0x00, 0x00,
}
