// Code generated by protoc-gen-go. DO NOT EDIT.
// source: responseCommand.proto

package io_radicalbit_nsdb_rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetricSchemaRetrieved_MetricField_FieldClassType int32

const (
	MetricSchemaRetrieved_MetricField_TIMESTAMP MetricSchemaRetrieved_MetricField_FieldClassType = 0
	MetricSchemaRetrieved_MetricField_VALUE     MetricSchemaRetrieved_MetricField_FieldClassType = 1
	MetricSchemaRetrieved_MetricField_DIMENSION MetricSchemaRetrieved_MetricField_FieldClassType = 2
	MetricSchemaRetrieved_MetricField_TAG       MetricSchemaRetrieved_MetricField_FieldClassType = 3
)

var MetricSchemaRetrieved_MetricField_FieldClassType_name = map[int32]string{
	0: "TIMESTAMP",
	1: "VALUE",
	2: "DIMENSION",
	3: "TAG",
}

var MetricSchemaRetrieved_MetricField_FieldClassType_value = map[string]int32{
	"TIMESTAMP": 0,
	"VALUE":     1,
	"DIMENSION": 2,
	"TAG":       3,
}

func (x MetricSchemaRetrieved_MetricField_FieldClassType) String() string {
	return proto.EnumName(MetricSchemaRetrieved_MetricField_FieldClassType_name, int32(x))
}

func (MetricSchemaRetrieved_MetricField_FieldClassType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6028948db234c6f5, []int{1, 0, 0}
}

type MetricsGot struct {
	Db                    string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace             string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Metrics               []string `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	CompletedSuccessfully bool     `protobuf:"varint,4,opt,name=completedSuccessfully,proto3" json:"completedSuccessfully,omitempty"`
	Errors                string   `protobuf:"bytes,5,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *MetricsGot) Reset()         { *m = MetricsGot{} }
func (m *MetricsGot) String() string { return proto.CompactTextString(m) }
func (*MetricsGot) ProtoMessage()    {}
func (*MetricsGot) Descriptor() ([]byte, []int) {
	return fileDescriptor_6028948db234c6f5, []int{0}
}

func (m *MetricsGot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsGot.Unmarshal(m, b)
}
func (m *MetricsGot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsGot.Marshal(b, m, deterministic)
}
func (m *MetricsGot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsGot.Merge(m, src)
}
func (m *MetricsGot) XXX_Size() int {
	return xxx_messageInfo_MetricsGot.Size(m)
}
func (m *MetricsGot) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsGot.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsGot proto.InternalMessageInfo

func (m *MetricsGot) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *MetricsGot) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *MetricsGot) GetMetrics() []string {
	if m != nil {
		return m.Metrics
	}
	return nil
}

func (m *MetricsGot) GetCompletedSuccessfully() bool {
	if m != nil {
		return m.CompletedSuccessfully
	}
	return false
}

func (m *MetricsGot) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type MetricSchemaRetrieved struct {
	Db                    string                               `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace             string                               `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Metric                string                               `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	Fields                []*MetricSchemaRetrieved_MetricField `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	CompletedSuccessfully bool                                 `protobuf:"varint,5,opt,name=completedSuccessfully,proto3" json:"completedSuccessfully,omitempty"`
	Errors                string                               `protobuf:"bytes,6,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                             `json:"-"`
	XXX_unrecognized      []byte                               `json:"-"`
	XXX_sizecache         int32                                `json:"-"`
}

func (m *MetricSchemaRetrieved) Reset()         { *m = MetricSchemaRetrieved{} }
func (m *MetricSchemaRetrieved) String() string { return proto.CompactTextString(m) }
func (*MetricSchemaRetrieved) ProtoMessage()    {}
func (*MetricSchemaRetrieved) Descriptor() ([]byte, []int) {
	return fileDescriptor_6028948db234c6f5, []int{1}
}

func (m *MetricSchemaRetrieved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricSchemaRetrieved.Unmarshal(m, b)
}
func (m *MetricSchemaRetrieved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricSchemaRetrieved.Marshal(b, m, deterministic)
}
func (m *MetricSchemaRetrieved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricSchemaRetrieved.Merge(m, src)
}
func (m *MetricSchemaRetrieved) XXX_Size() int {
	return xxx_messageInfo_MetricSchemaRetrieved.Size(m)
}
func (m *MetricSchemaRetrieved) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricSchemaRetrieved.DiscardUnknown(m)
}

var xxx_messageInfo_MetricSchemaRetrieved proto.InternalMessageInfo

func (m *MetricSchemaRetrieved) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *MetricSchemaRetrieved) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *MetricSchemaRetrieved) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *MetricSchemaRetrieved) GetFields() []*MetricSchemaRetrieved_MetricField {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *MetricSchemaRetrieved) GetCompletedSuccessfully() bool {
	if m != nil {
		return m.CompletedSuccessfully
	}
	return false
}

func (m *MetricSchemaRetrieved) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

type MetricSchemaRetrieved_MetricField struct {
	Name                 string                                           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FieldClassType       MetricSchemaRetrieved_MetricField_FieldClassType `protobuf:"varint,2,opt,name=fieldClassType,proto3,enum=io.radicalbit.nsdb.rpc.MetricSchemaRetrieved_MetricField_FieldClassType" json:"fieldClassType,omitempty"`
	IndexType            string                                           `protobuf:"bytes,3,opt,name=indexType,proto3" json:"indexType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                         `json:"-"`
	XXX_unrecognized     []byte                                           `json:"-"`
	XXX_sizecache        int32                                            `json:"-"`
}

func (m *MetricSchemaRetrieved_MetricField) Reset()         { *m = MetricSchemaRetrieved_MetricField{} }
func (m *MetricSchemaRetrieved_MetricField) String() string { return proto.CompactTextString(m) }
func (*MetricSchemaRetrieved_MetricField) ProtoMessage()    {}
func (*MetricSchemaRetrieved_MetricField) Descriptor() ([]byte, []int) {
	return fileDescriptor_6028948db234c6f5, []int{1, 0}
}

func (m *MetricSchemaRetrieved_MetricField) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricSchemaRetrieved_MetricField.Unmarshal(m, b)
}
func (m *MetricSchemaRetrieved_MetricField) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricSchemaRetrieved_MetricField.Marshal(b, m, deterministic)
}
func (m *MetricSchemaRetrieved_MetricField) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricSchemaRetrieved_MetricField.Merge(m, src)
}
func (m *MetricSchemaRetrieved_MetricField) XXX_Size() int {
	return xxx_messageInfo_MetricSchemaRetrieved_MetricField.Size(m)
}
func (m *MetricSchemaRetrieved_MetricField) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricSchemaRetrieved_MetricField.DiscardUnknown(m)
}

var xxx_messageInfo_MetricSchemaRetrieved_MetricField proto.InternalMessageInfo

func (m *MetricSchemaRetrieved_MetricField) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *MetricSchemaRetrieved_MetricField) GetFieldClassType() MetricSchemaRetrieved_MetricField_FieldClassType {
	if m != nil {
		return m.FieldClassType
	}
	return MetricSchemaRetrieved_MetricField_TIMESTAMP
}

func (m *MetricSchemaRetrieved_MetricField) GetIndexType() string {
	if m != nil {
		return m.IndexType
	}
	return ""
}

type Namespaces struct {
	Db                    string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespaces            []string `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	CompletedSuccessfully bool     `protobuf:"varint,3,opt,name=completedSuccessfully,proto3" json:"completedSuccessfully,omitempty"`
	Errors                string   `protobuf:"bytes,4,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Namespaces) Reset()         { *m = Namespaces{} }
func (m *Namespaces) String() string { return proto.CompactTextString(m) }
func (*Namespaces) ProtoMessage()    {}
func (*Namespaces) Descriptor() ([]byte, []int) {
	return fileDescriptor_6028948db234c6f5, []int{2}
}

func (m *Namespaces) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespaces.Unmarshal(m, b)
}
func (m *Namespaces) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespaces.Marshal(b, m, deterministic)
}
func (m *Namespaces) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespaces.Merge(m, src)
}
func (m *Namespaces) XXX_Size() int {
	return xxx_messageInfo_Namespaces.Size(m)
}
func (m *Namespaces) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespaces.DiscardUnknown(m)
}

var xxx_messageInfo_Namespaces proto.InternalMessageInfo

func (m *Namespaces) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *Namespaces) GetNamespaces() []string {
	if m != nil {
		return m.Namespaces
	}
	return nil
}

func (m *Namespaces) GetCompletedSuccessfully() bool {
	if m != nil {
		return m.CompletedSuccessfully
	}
	return false
}

func (m *Namespaces) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

func init() {
	proto.RegisterEnum("io.radicalbit.nsdb.rpc.MetricSchemaRetrieved_MetricField_FieldClassType", MetricSchemaRetrieved_MetricField_FieldClassType_name, MetricSchemaRetrieved_MetricField_FieldClassType_value)
	proto.RegisterType((*MetricsGot)(nil), "io.radicalbit.nsdb.rpc.MetricsGot")
	proto.RegisterType((*MetricSchemaRetrieved)(nil), "io.radicalbit.nsdb.rpc.MetricSchemaRetrieved")
	proto.RegisterType((*MetricSchemaRetrieved_MetricField)(nil), "io.radicalbit.nsdb.rpc.MetricSchemaRetrieved.MetricField")
	proto.RegisterType((*Namespaces)(nil), "io.radicalbit.nsdb.rpc.Namespaces")
}

func init() { proto.RegisterFile("responseCommand.proto", fileDescriptor_6028948db234c6f5) }

var fileDescriptor_6028948db234c6f5 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcd, 0xae, 0x93, 0x40,
	0x14, 0x16, 0x86, 0x72, 0xe5, 0xdc, 0x48, 0xc8, 0x24, 0x6d, 0x26, 0xc6, 0x18, 0xc2, 0x8a, 0x15,
	0x8b, 0xab, 0x1b, 0x97, 0xf5, 0xda, 0xd6, 0x26, 0x52, 0x15, 0xd0, 0x3d, 0xcc, 0x4c, 0x23, 0x09,
	0x30, 0x64, 0x86, 0x1a, 0xfb, 0x0a, 0x3e, 0x86, 0xef, 0xa8, 0x6b, 0xc3, 0x4f, 0x2d, 0xd5, 0x36,
	0xa9, 0x77, 0x37, 0xe7, 0x9b, 0xcc, 0x77, 0xbe, 0x1f, 0x80, 0xa9, 0xe4, 0xaa, 0x16, 0x95, 0xe2,
	0xf7, 0xa2, 0x2c, 0xd3, 0x8a, 0x05, 0xb5, 0x14, 0x8d, 0xc0, 0xb3, 0x5c, 0x04, 0x32, 0x65, 0x39,
	0x4d, 0x8b, 0x2c, 0x6f, 0x82, 0x4a, 0xb1, 0x2c, 0x90, 0x35, 0xf5, 0x7e, 0x68, 0x00, 0x21, 0x6f,
	0x64, 0x4e, 0xd5, 0x4a, 0x34, 0xd8, 0x06, 0x9d, 0x65, 0x44, 0x73, 0x35, 0xdf, 0x8a, 0x74, 0x96,
	0xe1, 0x67, 0x60, 0x55, 0x69, 0xc9, 0x55, 0x9d, 0x52, 0x4e, 0xf4, 0x0e, 0x3e, 0x02, 0x98, 0xc0,
	0x4d, 0xd9, 0xbf, 0x25, 0xc8, 0x45, 0xbe, 0x15, 0x1d, 0x46, 0xfc, 0x12, 0xa6, 0x54, 0x94, 0x75,
	0xc1, 0x1b, 0xce, 0xe2, 0x1d, 0xa5, 0x5c, 0xa9, 0xed, 0xae, 0x28, 0xf6, 0xc4, 0x70, 0x35, 0xff,
	0x71, 0x74, 0xfe, 0x12, 0xcf, 0xc0, 0xe4, 0x52, 0x0a, 0xa9, 0xc8, 0xa4, 0x5b, 0x35, 0x4c, 0xde,
	0x2f, 0x04, 0xd3, 0x5e, 0x64, 0x4c, 0xbf, 0xf0, 0x32, 0x8d, 0xda, 0x33, 0xff, 0xca, 0xd9, 0x7f,
	0xea, 0x9d, 0x81, 0xd9, 0x0b, 0x24, 0xa8, 0xe7, 0xef, 0x27, 0xfc, 0x11, 0xcc, 0x6d, 0xce, 0x0b,
	0xa6, 0x88, 0xe1, 0x22, 0xff, 0xf6, 0xee, 0x55, 0x70, 0x3e, 0xad, 0xe0, 0xac, 0x88, 0x01, 0x5d,
	0xb6, 0x0c, 0xd1, 0x40, 0x74, 0x39, 0x80, 0xc9, 0x75, 0x01, 0x98, 0xe3, 0x00, 0x9e, 0xfe, 0xd4,
	0xe0, 0x76, 0xb4, 0x05, 0x63, 0x30, 0x5a, 0x57, 0x83, 0xf1, 0xee, 0x8c, 0x6b, 0xb0, 0xbb, 0xdd,
	0xf7, 0x45, 0xaa, 0x54, 0xb2, 0xaf, 0x7b, 0xff, 0xf6, 0xdd, 0xdb, 0x07, 0x9b, 0x09, 0x96, 0x27,
	0x7c, 0xd1, 0x5f, 0xfc, 0x6d, 0xd8, 0x79, 0xc5, 0xf8, 0xb7, 0x6e, 0x59, 0x9f, 0xe8, 0x11, 0xf0,
	0x5e, 0x83, 0x7d, 0xfa, 0x1e, 0x3f, 0x01, 0x2b, 0x59, 0x87, 0x8b, 0x38, 0x99, 0x87, 0x1f, 0x9c,
	0x47, 0xd8, 0x82, 0xc9, 0xe7, 0xf9, 0xbb, 0x4f, 0x0b, 0x47, 0x6b, 0x6f, 0xde, 0xac, 0xc3, 0xc5,
	0x26, 0x5e, 0xbf, 0xdf, 0x38, 0x3a, 0xbe, 0x01, 0x94, 0xcc, 0x57, 0x0e, 0xf2, 0xbe, 0x6b, 0x00,
	0x9b, 0x43, 0x7d, 0xea, 0x9f, 0xb6, 0x9f, 0x03, 0xfc, 0x29, 0x57, 0x11, 0xbd, 0xfb, 0x04, 0x47,
	0xc8, 0xe5, 0x12, 0xd0, 0x75, 0x25, 0x18, 0xe3, 0x12, 0x32, 0xb3, 0xfb, 0x93, 0x5e, 0xfc, 0x0e,
	0x00, 0x00, 0xff, 0xff, 0x45, 0x9a, 0x4c, 0x22, 0x62, 0x03, 0x00, 0x00,
}
