// Code generated by protoc-gen-go. DO NOT EDIT.
// source: responseSQL.proto

package io_radicalbit_nsdb_rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SQLStatementResponse struct {
	Db                    string   `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Namespace             string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Metric                string   `protobuf:"bytes,3,opt,name=metric,proto3" json:"metric,omitempty"`
	CompletedSuccessfully bool     `protobuf:"varint,4,opt,name=completedSuccessfully,proto3" json:"completedSuccessfully,omitempty"`
	Reason                string   `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Message               string   `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	Records               []*Bit   `protobuf:"bytes,7,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SQLStatementResponse) Reset()         { *m = SQLStatementResponse{} }
func (m *SQLStatementResponse) String() string { return proto.CompactTextString(m) }
func (*SQLStatementResponse) ProtoMessage()    {}
func (*SQLStatementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_034383820e99c319, []int{0}
}

func (m *SQLStatementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SQLStatementResponse.Unmarshal(m, b)
}
func (m *SQLStatementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SQLStatementResponse.Marshal(b, m, deterministic)
}
func (m *SQLStatementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SQLStatementResponse.Merge(m, src)
}
func (m *SQLStatementResponse) XXX_Size() int {
	return xxx_messageInfo_SQLStatementResponse.Size(m)
}
func (m *SQLStatementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SQLStatementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SQLStatementResponse proto.InternalMessageInfo

func (m *SQLStatementResponse) GetDb() string {
	if m != nil {
		return m.Db
	}
	return ""
}

func (m *SQLStatementResponse) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *SQLStatementResponse) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *SQLStatementResponse) GetCompletedSuccessfully() bool {
	if m != nil {
		return m.CompletedSuccessfully
	}
	return false
}

func (m *SQLStatementResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *SQLStatementResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SQLStatementResponse) GetRecords() []*Bit {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*SQLStatementResponse)(nil), "io.radicalbit.nsdb.rpc.SQLStatementResponse")
}

func init() { proto.RegisterFile("responseSQL.proto", fileDescriptor_034383820e99c319) }

var fileDescriptor_034383820e99c319 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4e, 0xc3, 0x30,
	0x10, 0xc6, 0x95, 0x14, 0x12, 0x6a, 0x10, 0x12, 0x16, 0x54, 0x16, 0x30, 0x44, 0x4c, 0x99, 0x3c,
	0xf0, 0xe7, 0x05, 0x98, 0xbb, 0x34, 0x79, 0x02, 0xfb, 0x7c, 0x20, 0x4b, 0xb1, 0xcf, 0xf2, 0xb9,
	0x03, 0xcf, 0xce, 0x82, 0x48, 0x5a, 0x75, 0xe9, 0xf8, 0x7d, 0xbf, 0x4f, 0x3f, 0xe9, 0x4e, 0xdc,
	0x65, 0xe4, 0x44, 0x91, 0x71, 0xdc, 0x6d, 0x75, 0xca, 0x54, 0x48, 0x6e, 0x3c, 0xe9, 0x6c, 0x9c,
	0x07, 0x33, 0x59, 0x5f, 0x74, 0x64, 0x67, 0x75, 0x4e, 0xf0, 0x78, 0x03, 0x14, 0x02, 0xc5, 0x65,
	0xf5, 0xf2, 0x5b, 0x89, 0xfb, 0x71, 0xb7, 0x1d, 0x8b, 0x29, 0x18, 0x30, 0x96, 0xe1, 0xe0, 0x91,
	0xb7, 0xa2, 0x76, 0x56, 0x55, 0x5d, 0xd5, 0xaf, 0x87, 0xda, 0x59, 0xf9, 0x2c, 0xd6, 0xd1, 0x04,
	0xe4, 0x64, 0x00, 0x55, 0x3d, 0xd7, 0xa7, 0x42, 0x6e, 0x44, 0x13, 0xb0, 0x64, 0x0f, 0x6a, 0x35,
	0xa3, 0x43, 0x92, 0xef, 0xe2, 0x01, 0x28, 0xa4, 0x09, 0x0b, 0xba, 0x71, 0x0f, 0x80, 0xcc, 0x5f,
	0xfb, 0x69, 0xfa, 0x51, 0x17, 0x5d, 0xd5, 0x5f, 0x0d, 0xe7, 0xe1, 0xbf, 0x2d, 0xa3, 0x61, 0x8a,
	0xea, 0x72, 0xb1, 0x2d, 0x49, 0x2a, 0xd1, 0x06, 0x64, 0x36, 0xdf, 0xa8, 0x9a, 0x19, 0x1c, 0xa3,
	0xfc, 0x10, 0x6d, 0x46, 0xa0, 0xec, 0x58, 0xb5, 0xdd, 0xaa, 0xbf, 0x7e, 0x7d, 0xd2, 0xe7, 0xcf,
	0xd7, 0x9f, 0xbe, 0x0c, 0xc7, 0xad, 0x6d, 0xe6, 0x27, 0xbc, 0xfd, 0x05, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0x53, 0x6d, 0x39, 0x3f, 0x01, 0x00, 0x00,
}
