// Code generated by protoc-gen-go. DO NOT EDIT.
// source: response.proto

package io_radicalbit_nsdb_rpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RPCInsertResult struct {
	CompletedSuccessfully bool     `protobuf:"varint,1,opt,name=completedSuccessfully,proto3" json:"completedSuccessfully,omitempty"`
	Errors                string   `protobuf:"bytes,2,opt,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *RPCInsertResult) Reset()         { *m = RPCInsertResult{} }
func (m *RPCInsertResult) String() string { return proto.CompactTextString(m) }
func (*RPCInsertResult) ProtoMessage()    {}
func (*RPCInsertResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fbc901015fa5021, []int{0}
}

func (m *RPCInsertResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RPCInsertResult.Unmarshal(m, b)
}
func (m *RPCInsertResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RPCInsertResult.Marshal(b, m, deterministic)
}
func (m *RPCInsertResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RPCInsertResult.Merge(m, src)
}
func (m *RPCInsertResult) XXX_Size() int {
	return xxx_messageInfo_RPCInsertResult.Size(m)
}
func (m *RPCInsertResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RPCInsertResult.DiscardUnknown(m)
}

var xxx_messageInfo_RPCInsertResult proto.InternalMessageInfo

func (m *RPCInsertResult) GetCompletedSuccessfully() bool {
	if m != nil {
		return m.CompletedSuccessfully
	}
	return false
}

func (m *RPCInsertResult) GetErrors() string {
	if m != nil {
		return m.Errors
	}
	return ""
}

func init() {
	proto.RegisterType((*RPCInsertResult)(nil), "io.radicalbit.nsdb.rpc.RPCInsertResult")
}

func init() { proto.RegisterFile("response.proto", fileDescriptor_0fbc901015fa5021) }

var fileDescriptor_0fbc901015fa5021 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xcb, 0xcc, 0xd7, 0x2b,
	0x4a, 0x4c, 0xc9, 0x4c, 0x4e, 0xcc, 0x49, 0xca, 0x2c, 0xd1, 0xcb, 0x2b, 0x4e, 0x49, 0xd2, 0x2b,
	0x2a, 0x48, 0x56, 0x8a, 0xe7, 0xe2, 0x0f, 0x0a, 0x70, 0xf6, 0xcc, 0x2b, 0x4e, 0x2d, 0x2a, 0x09,
	0x4a, 0x2d, 0x2e, 0xcd, 0x29, 0x11, 0x32, 0xe1, 0x12, 0x4d, 0xce, 0xcf, 0x2d, 0xc8, 0x49, 0x2d,
	0x49, 0x4d, 0x09, 0x2e, 0x4d, 0x4e, 0x4e, 0x2d, 0x2e, 0x4e, 0x2b, 0xcd, 0xc9, 0xa9, 0x94, 0x60,
	0x54, 0x60, 0xd4, 0xe0, 0x08, 0xc2, 0x2e, 0x29, 0x24, 0xc6, 0xc5, 0x96, 0x5a, 0x54, 0x94, 0x5f,
	0x54, 0x2c, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0xe5, 0x25, 0xb1, 0x81, 0xed, 0x37, 0x06,
	0x04, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xff, 0x9b, 0x53, 0x91, 0x00, 0x00, 0x00,
}
